- project:
    templates:
      - sf-ci-jobs
      - sf-ci-packages-publish
    check:
      jobs:
        - swagger-lint:
            vars:
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
        - tox-py36:
            nodeset: python-latest-pod
        - tox-pep8:
            nodeset: python-latest-pod
    gate:
      jobs:
        - tox-py36:
            nodeset: python-latest-pod
        - tox-pep8:
            nodeset: python-latest-pod
        - swagger-lint:
            vars:
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
        - swagger-publish:
            dependencies:
              - swagger-lint
            vars:
              swagger_api: manageSF
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
