- project:
    templates:
      - sf-ci-jobs
      - sf-ci-packages-publish
    check:
      jobs:
        - swagger-lint:
            vars:
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
        - tox-py36:
            nodeset: fedora-latest-runc
        - tox-pep8:
            nodeset: fedora-latest-runc
    gate:
      jobs:
        - tox-py36:
            nodeset: fedora-latest-runc
        - tox-pep8:
            nodeset: fedora-latest-runc
        - swagger-lint:
            vars:
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
        - swagger-publish:
            dependencies:
              - swagger-lint
            vars:
              swagger_api: manageSF
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
