- project:
    check:
      jobs:
        - swagger-lint:
            vars:
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
            nodeset:
              nodes:
                - name: pod-centos
                  label: pod-centos-7
        - tox-py27:
            voting: false
            nodeset:
              nodes:
                - name: pod-centos
                  label: pod-centos-7
