- project:
    check:
      jobs:
        - swagger-lint:
            vars:
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
            nodeset: centos-latest-pod
        - tox-py27:
            voting: false
            nodeset: centos-latest-pod
        - tox-py36:
            nodeset: centos-latest-pod
        - tox-pep8:
            nodeset: centos-latest-pod
