- project:
    templates:
      - sf-ci-jobs
      - sf-ci-packages-publish
    check:
      jobs:
        - swagger-lint:
            vars:
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
        - tox-py36:
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-ubi7
            required-projects:
              - software-factory/pynotedb
        - tox-pep8:
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-ubi7
    gate:
      jobs:
        - tox-py36:
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-ubi7
            required-projects:
              - software-factory/pynotedb
        - tox-pep8:
            nodeset:
              nodes:
                - name: testrunner
                  label: zuul-worker-ubi7
        - swagger-lint:
            vars:
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
        - swagger-publish:
            dependencies:
              - swagger-lint
            vars:
              swagger_api: manageSF
              swagger_file: "docs/swagger/managesf.v2.yaml"
            files:
              - "docs/swagger/managesf.v2.yaml"
    release:
      jobs:
        - upload-pypi
